### ISSUE TITLE
Release 4.0.0.rc.1

### ISSUE THREAD

**Issue by fredjean** [fredjean/middleman-s3_sync#104]
I am considering yanking the current 4.0.0 gem and replacing it with a 4.0.0.rc.1 version of the same.

Middleman is still in the RC phase, and it is slightly misleading to advertise a version of the gem that may not work with Middleman 4.0.0 final. This means that it is likely that Middleman S3_Sync will be released as 4.0.1.

**Comment by johnnyshields** [comment]
Yanking is a pain, why not just release the next one as 4.1.0.rc.1

**Comment by johnnyshields** [comment]
@fredjean can you please make a release?

**Comment by fredjean** [comment]
4.0.1.rc.1 has been released to Rubygems.
