### ISSUE TITLE
bundle exec middleman s3_sync --build. not working

### ISSUE THREAD

**Issue by Tejs** [fredjean/middleman-s3_sync#120]
Hi, I'm trying to run a build before the sync like it says here:
https://github.com/fredjean/middleman-s3_sync#run-build-before-synchronizing

I use this command:
bundle exec middleman s3_sync --build

It returns:
Unknown switches '--build'

This command work well:
bundle exec middleman s3_sync --dry_run
So it seems to be specifically related to the --build

**Comment by fredjean** [comment]
What version of middleman s3_sync are you using?

**Comment by Tejs** [comment]
middleman-s3_sync-3.3.9

**Comment by fredjean** [comment]
I'll have to check, but I'm not entirely sure that it was backported to the v3.3.x branch.

**Comment by Tejs** [comment]
This is definitely my mistake, seems like I'm running middleman in an old version.
I'll update it – sorry for the inconvenience!
