### ISSUE TITLE
Alternative that doesn't depend on Middleman

### ISSUE THREAD

**Issue by monfresh** [fredjean/middleman-s3_sync#127]
Hi Frederic. This isn't really an issue. I just wanted to share with you a really cool gem I came across that works exactly like anyone would expect it to. What's great about it is that it supports S3 sync, cloudfront invalidation, redirects, and a lot more, and doesn't depend on any specific type of static site generator. 

The lack of dependencies makes sense since really all you're dealing with are static files. That way, if Middleman changes, the gem will still keep working, as opposed to gems that are tied to the generator itself, which would require making changes to support Middleman 4 vs 3 for example.  

I've been using it for my Middleman sites and it works wonderfully. Take a look and see what you think:
https://github.com/laurilehmijoki/s3_website

**Comment by fredjean** [comment]
Hi @monfresh . My apologies for not responding earlier.

I think that it's a good solution. I haven't looked deeply at the source to see whether it uses a similar set of rules to figure out which files have changed and need to be updated, but that might not necessarily matter to you.

I considered splitting s3_sync into parts that rely on Middleman and parts that do not, but I haven't found the energy to do so.

I'm glad you found something that works well for you.
