### ISSUE TITLE
Patch to set S3 redirects?

### ISSUE THREAD

**Issue by mathie** [fredjean/middleman-s3_sync#129]
I've wound up monkey patching Middleman & s3sync to support setting `x-amz-website-redirect-location` on resources configured with the `redirect` method in `config.rb`:https://github.com/wossname/woss.name/blob/master/helpers/s3_redirects.rb. Is that the sort of thing I should be tidying up into a pull request at some point?

**Comment by fredjean** [comment]
Absolutely. I haven't been paying any attention to s3_redirect and merging this into s3_sync makes a lot of sense.

**Comment by mathie** [comment]
Awesome. In which case, I'll tidy it up into a pull request. 😄

**Comment by umerebryx** [comment]
@mathie I was using https://github.com/fredjean/middleman-s3_redirect for setting up redirects on my s3 bucket. Can your PR be used as an alternative for this? If yes, is there any documentation/example I can use to setup my project?

**Comment by umerebryx** [comment]
Thanks @matiasgarciaisaia , I got the redirects to work locally. But when I use s3_sync to update my s3 bucket these redirects are not synced. I am also calling `sitemap.ensure_resource_list_updated!` right after redirects:

> redirect 'jobs/account-manager/index.html', to: '/jobs/umer/index.html'
> sitemap.ensure_resource_list_updated!

Is it possible I have to add above block at a certain place in my config.rb?

**Comment by matiasgarciaisaia** [comment]
My only suggestion is to run the `s3_sync` in verbose mode and share the output to check what could be going on.

**Comment by pwim** [comment]
@umerebryx I also ran in to this issue, but realized it is because the most recent release doesn't contain the PR that adds support. I've created #158 to ask for a new version to be released. In the meantime, you can use it if you specify to use the github version:

``` ruby
gem 'middleman-s3_sync', github: "fredjean/middleman-s3_sync"
```
