### ISSUE TITLE
Allow specific Content-Type and Charset for certain files

### ISSUE THREAD

**Issue by fredjean** [fredjean/middleman-s3_sync#7]
> Is there a way to support setting the Content-Type too? Or is this already possible? I would like to set Content-Type to 'text/html;charset=utf-8' for some files in the bucket.

@cutemachine Could you elaborate on this? Are you looking to set the content based on path? glob? extension? We are already setting the content type based on the extension of the file (which is also done by fog as well). I do not think that we are setting the charset at this point though. Ideas on what you would like this to look like would be good.

Thanks!

**Comment by gkop** [comment]
+1, this gem is awesome, this feature would make it more awesome.

My use case is avoiding using Middleman's [directory indexes](https://middlemanapp.com/advanced/pretty_urls/) feature to produce extension-less URLs. With directory indexes and s3, [s3 redirects adding an ugly trailing /](https://docs.aws.amazon.com/AmazonS3/latest/dev/IndexDocumentSupport.html). In fact, this ugly behavior is even present on the Middleman docs: visit https://middlemanapp.com/advanced/pretty_urls and notice the redirect adding the trailing forward slash (I'm not sure they are using s3, they have a cdn in front of whatever host they are using). This is a characteristic of s3; in contrast, nginx out-of-the-box will serve the directory indexes directly.

**Comment by leighmcculloch** [comment]
I've been using the very minimal changes in pull request #87 on a middleman site of ~500 dynamic pages that don't have extensions to set the content-type explicitly. It's not a perfect solution but I think it's a good-enough filler until the rewrite of the gem supporting the new Middleman callbacks.
