### ISSUE TITLE
undefined method 'green' - recent ansi change

### ISSUE THREAD

**Issue by ElaineYu** [fredjean/middleman-s3_sync#71]
Hello!  I'm getting this error:
in `say_status': undefined method `green' for "     s3_sync":String (NoMethodError)

after running this command:
bundle exec middleman s3_sync --bucket=my-aws-bucket-name

I believe this recent ANSI change is breaking the upload.  
https://github.com/fredjean/middleman-s3_sync/commit/6f78401145b24a5b9230636bdde7eab9993c7f6c

Thanks in advance!  Hope you have a happy new year!

**Comment by fredjean** [comment]
Can you point your middleman-s3_sync gem to this repo and try to run it again. I want to see whether my changes resolved them.

Here's the line that I use on my blog's Gemfile:

```ruby
gem "middleman-s3_sync", :git => "https://github.com/fredjean/middleman-s3_sync.git", :branch => :master
```

I'll push a new release if this works for you as well.

**Comment by rossf7** [comment]
Hi, I just hit the same error and using the repo version fixes it for me.  Thanks and Happy New Year!

**Comment by fredjean** [comment]
I'm glad it helped. I will push a new release later today.

Happy new year!

-- Fred

**Comment by fredjean** [comment]
And I just released 3.0.40 to Rubygems.

**Comment by ElaineYu** [comment]
Thanks @fredjean!  You're awesome!  Hope you had a happy new year!

**Comment by fredjean** [comment]
@ElaineYu Thank you for raising the issue! I hope you had a happy new year as well.
