### ISSUE TITLE
Middleman 4 compatibility

### ISSUE THREAD

**Issue by alex88** [fredjean/middleman-s3_sync#76]
Hi there, I've seen you're actually working on mm4 support, any hint in how to use it already? is it possible?

Using your mm4 branch I can't run s3 sync since I get `Could not find command "s3_sync"`

**Comment by fredjean** [comment]
It's definitively a work in progress and it is not ready for use.

Middleman 4 is going to drop some of the APIs that s3_sync is using, so
there is a bit of a deadline in adapting the gem to the new ones. I
haven't been able to work on it for the last few weeks, but my calendar
is looking lighter and I should be able to get back to it.

Thanks!

Fred

Alessandro Tagliapietra wrote:

**Comment by alex88** [comment]
Thanks for the update man! Looking forward to it! Great work! ;)
