### ISSUE TITLE
Proper IAM Roles usage

### ISSUE THREAD

**Issue by Fodoj** [fredjean/middleman-s3_sync#84]
Currently it seems like IAM Roles are not supported, thought I might be wrong. I am already on EC2 instance, so I don't want to store my access keys on the instance and use IAM Roles and Policies instead. Am I right that at the moment this feature is not supported?

**Comment by fredjean** [comment]
You are correct. It appears to be somewhat easy to add.

**Comment by Fodoj** [comment]
I will provide a PR then

**Comment by Fodoj** [comment]
See attached PR. I am closing this issue.
