### ISSUE TITLE
Override prefix via a new switch?

### ISSUE THREAD

**Issue by pixelsonly** [fredjean/middleman-s3_sync#86]
Just curious, I've run across a need for this use case but I'm not sure how difficult it would be to implement.

**Comment by fredjean** [comment]
Can you expand on what you mean?

**Comment by pixelsonly** [comment]
@fredjean I just noticed the title didn't make any sense. What I meant to ask was if would be possible to override the prefix option via the CLI just like we can the bucket name?

**Comment by fredjean** [comment]
Sure. The only reason it's not here is that no one asked for it! I'll add it tonight.

**Comment by pixelsonly** [comment]
@fredjean very cool, I can't tell you how much I appreciate this!

**Comment by fredjean** [comment]
I can't get to it tonight, but I'll address it first thing in the morning.

**Comment by fredjean** [comment]
Sorry for  the delay. I just pushed version 3.0.46 which includes support for this new switch.
