### ISSUE TITLE
`content_type': undefined method `content_type' for nil:NilClass

### ISSUE THREAD

**Issue by naxIO** [fredjean/middleman-s3_sync#91]
Hey,

not sure if its me or a general problem. getting this while using middleman s3_sync --force

Build directory is present. It starts to sync some files and then:

```
/Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync/resource.rb:214:in `content_type': undefined method `content_type' for nil:NilClass (NoMethodError)
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync/resource.rb:34:in `to_h'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync/resource.rb:62:in `block in update!'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync/resource.rb:126:in `open'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync/resource.rb:126:in `local_content'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync/resource.rb:60:in `update!'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync.rb:139:in `block in update_resources'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync.rb:138:in `each'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync.rb:138:in `update_resources'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman/s3_sync.rb:40:in `sync'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-s3_sync-3.3.0/lib/middleman-s3_sync/commands.rb:54:in `s3_sync'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:72:in `method_missing'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.4.0/lib/middleman-core/cli.rb:20:in `start'
	from /Users/chris/.rvm/gems/ruby-2.2.3/gems/middleman-core-3.4.0/bin/middleman:18:in `<top (required)>'
	from /Users/chris/.rvm/gems/ruby-2.2.3/bin/middleman:23:in `load'
	from /Users/chris/.rvm/gems/ruby-2.2.3/bin/middleman:23:in `<main>'
	from /Users/chris/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `eval'
	from /Users/chris/.rvm/gems/ruby-2.2.3/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by fredjean** [comment]
I tried to reproduce on my side but I couldn't. 

What is the file that it was trying to update? Is the file itself present on the bucket? Is it present in the build directory?

Thanks!

-- Fred

**Comment by naxIO** [comment]
Gonna check, this could be it. I tied to find the file via a verbose option but no success. will test tonight. thanks

**Comment by naxIO** [comment]
Hmm how can I debug this? is there a --verbose option?

**Comment by fredjean** [comment]
There is, but I am not sure that it is going to print interesting results.

I'll see if I can catch the exception (or verify that the resource is not null before calling content_type).

**Comment by fredjean** [comment]
Could you try updating to v3.3.2? The code to determine whether a resource was local was modified to address that very issue.

**Comment by naxIO** [comment]
Now its working without an error. I have no idea why. I just upgraded (v3.3.3) and nothing more. Will get back but I think for no (hopefully forever) its solved. Thanks for your work on this :)

**Comment by naxIO** [comment]
Well, lol. I was a bit too fast. While everything works now s3_sync is no longer syncing my gzip files (and deleted them on S3 aswell). Did something change there with v3.3.3? Shall I open a new issue? Thanks

**Comment by fredjean** [comment]
How are the gzipped files created? Are they in the source folder or are they copied into the build folder as part of your build process?

Having access to the repo (or doing a screenhero session) might help.

**Comment by naxIO** [comment]
I use 
´´´
configure :build do
  activate :gzip
´´´

and did no changes there. The .gz are present in the build folder like

´´´
index.html
index.html.gz
´´´

it worked well in the previous version of this gem.

Thank you :)

**Comment by fredjean** [comment]
s3_sync is now using the sitemap to figure out what files to push instead of looking for the files that on the build directory. When the `prefer_gzip` option is set, s3_sync looks for a .gz file and will push it's content up to S3 and set the appropriate meta-data. Otherwise it will push the non-compressed file.

S3 doesn't support content encoding negotiation at this point, but pushing the compressed file to S3 with the original file name and the appropriate headers is sufficient to serve compressed content to the browser. Otherwise the .gz files are just ignored.

My recommendation would be to set the `prefer_gzip` option to true and verify that the content is properly encoded (which I can do quickly if you point me to the URL for the web site).

**Comment by naxIO** [comment]
Hi, thanks for the info.

In my config I have 
´´´
s3_sync.prefer_gzip = true
´´´´

Probably its working now

´´´
 s3_sync  Updating index.html (gzipped)
´´´

Website is www.schepan.com you can check if you want :+1: thanks
