### ISSUE TITLE
Improve documentation or add warning on `prefix` option

### ISSUE THREAD

**Issue by ludwigschubert** [fredjean/middleman-s3_sync#94]
When specifying a prefix such as `folder` I needed to add a trailing slash.
Is this intended behavior? If so, should we ammend documentation to mention this? I could also imagine a warning on the console, would this interfere with any intended usage, though?

Also: thanks for an otherwise awesomely simple deployment tool!

**Comment by fredjean** [comment]
I'll add some code that will ensure that there is a / at the end of the prefix.

**Comment by fredjean** [comment]
v3.3.3 has the code that adds / at the end of the prefix if needed.
