### ISSUE TITLE
Caching policy for text/html only works if you add `; charset=utf-8`

### ISSUE THREAD

**Issue by monfresh** [fredjean/middleman-s3_sync#96]
When I specified the following caching policy:
```
caching_policy 'text/html', max_age: 86400, must_revalidate: true
```
it did not set the Cache-Control headers on S3.

Then, I noticed that the Content-Type on S3 was listed as `text/html; charset=utf-8`, so I updated the policy to this:
```
caching_policy 'text/html; charset=utf-8', max_age: 86400, must_revalidate: true
```
and it worked.

Ideally, the policy would work with just `text/html`.

**Comment by fredjean** [comment]
It is a result of getting the content type from the Middleman resource object. The fix should be pretty easy. I'll address it in a follow up to 3.3.3 and make sure that the fix is carried over to the 4.0.x stream.

**Comment by heypiotr** [comment]
I've just run into the same issue. Any news here?

**Comment by fredjean** [comment]
v3.3.7 should address this particular issue.

**Comment by mschewe** [comment]
I am getting the following error:
```
s3_sync  Creating .htaccess
[...]/2.2.3/lib/ruby/gems/2.2.0/gems/middleman-s3_sync-3.3.7/lib/middleman/s3_sync/caching_policy.rb:11:in `caching_policy_for': undefined method `strip' for nil:NilClass (NoMethodError)
```

May be you should use something like this:

```ruby
caching_policies.fetch(content_type.to_s.split(';').try(:first).try(:strip), caching_policies[:default])
```
It looks ugly but would prevent the error.

**Comment by andreas-venturini** [comment]
@fredjean same error on v.3.3.7 (latest from master)

```
Processing sitemap: |==================================================/cache/ruby/2.1.0/gems/middleman-s3_sync-3.3.7/lib/middleman/s3_sync/caching_policy.rb:11:in `caching_policy_for': undefined method `strip' for nil:NilClass (NoMethodError)
```

**Comment by fredjean** [comment]
v3.3.8 addresses this.
