### ISSUE TITLE
Syncing to nameless directory

### ISSUE THREAD

**Issue by balthisar** [fredjean/middleman-s3_sync#97]
This strange; I've been using s3_sync for close to a year. Today I fresh installed a Ruby environment, updated my site to middleman 3.4.0, and s3_sync to 3.3.3.

Now when I bundle exec middleman s3_sync items are synced to a top level directory that doesn't have a name. I've always used `s3_sync.prefix = ''` in my `config.rb` without issues.

I've simply commented it out which I guess is forcing nil or null, and it seems to be syncing to the root level of my bucket right now.

**Comment by fredjean** [comment]
I'll update this in a follow up to the 3.3.3 release.

**Comment by balthisar** [comment]
Thanks. I've not looked into it myself as the workaround is working.

**Comment by dannguyen** [comment]
Just for reference for anyone else who runs into this...@balthisar's [fix is still needed and still works](https://github.com/fredjean/middleman-s3_sync/issues/97#issue-112305360) for version 4.0.x and Middleman 4.x

**Comment by aarti** [comment]
I sent a PR for this bug

**Comment by rossedman** [comment]
:+1: Thank you for this fix.
